### ISSUE TITLE
make pull request into MITgcm

### ISSUE THREAD

**Issue by ifenty** [mjlosch/optim_m1qn3#1]
Let's just call it optim_m1qn3.

You can always just make the request!

Ian

**Comment by mjlosch** [comment]
@ifenty I think it's fine as a separate repo, gives me a little more liberty for changing it around (as I just did). However, I should probably add a short section to the documentation, so that it is found.
@christophernhill What do you think?

**Comment by mjlosch** [comment]
There's now a link to this package in the documentation: https://mitgcm.readthedocs.io/en/latest/ocean_state_est/ocean_state_est.html#alternative-code-to-optim-and-lsopt
