### ISSUE TITLE
The value of "global fc" remains unchanged

### ISSUE THREAD

**Issue by LemingVan** [mjlosch/optim_m1qn3#7]
Hello @mjlosch ,

I'm new to model optimization (or adjoint model), thanks to your tutorial, I installed the `optim_m1qn3` successfully in WSL' Ubuntu 18.04.

I used the [OpenAD](https://github.com/dorugeber/OpenAD) to compile MITgcm-checkpoint67r/verification/tutorial_global_oce_optim, but the result of `global fc` looks differernt from yours, and the value is a constant, is this an error in my steps?
![out](https://user-images.githubusercontent.com/46369483/131250506-1bfd6839-2540-41af-91fe-18e39c61d1c9.png)

I compared the first (optimcycle=0) and last (optimcycle=19) SST and they came out exactly the same, which confused me a bit and I don't know how to determine the optimization effect. Could you tell me how to determine `optim_m1qn3` has been applied to the model correctly?

**Comment by LemingVan** [comment]
Thanks to @dorugeber, problem solved!  

The problem arises in the OpenAD module of MITgcm, just follow the method used by @dorugeber to modify the following two files.

https://github.com/dorugeber/MITgcm/commit/8746996fbe5eb81424a91c2138d966f86aa9a444
https://github.com/dorugeber/MITgcm/commit/b22bdca09cba404a9bff4b62772a27022b2d040a

![output](https://user-images.githubusercontent.com/46369483/132607237-ada57f80-bfae-4c98-b738-4a2b993882ef.png)

**Comment by mjlosch** [comment]
Thanks, @LemingVan 
Do you think you could add this information somewhere to the README instructions? This would be very helpful!

BTW, how did you manage to install and run OpenAD. I have been trying this for years without any success.

**Comment by dorugeber** [comment]
@mjlosch just popping in here, as Leming emailed me recently.

IIRC there were a couple of things required to get an OpenAD install:
1) change the Boost URL to include https: https://github.com/dorugeber/OpenAD/commit/0b3c46e38fbdfa6843ffdd4476dfc844e7689108
2) that version of Boost doesn't work with GCC 5 or newer, so download some GCC 4.x through your package manager, e.g. on Ubuntu 18.04:
`sudo apt install gcc-4.8 gfortran-4.8 g++-4.8    # for OpenAD`
followed by some messing around with `update-alternatives` to switch between "new" and "old" GCCs:
```
Keep multiple compiler versions around:
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8

Set GCC (or MPIrun):
sudo update-alternatives --config gcc
```
(I once tried updating this to the newest Boost, but OpenAD wouldn't build... this was in 2017, so unlikely to work now either!)

Use old GCC for the OpenAD build (only needs to be done once).  New GCC is fine for MITgcm.

**Comment by LemingVan** [comment]
Hi @mjlosch, I was busy a while ago, sorry for the late reply, here are my notes. And I'd like to take this opportunity to thank @dorugeber  and @DanJonesOcean for their kind help.

MITgcm version: `MITgcm-checkpoint67r`, Build Environment: `Windows 10 - WSL Ubuntu-18.04`, Using OpenAD & optim_m1qn3.

### 1. install OpenAD (only gcc-4.8 & g++-4.8 & gfortran-4.8 work)
```
1.0 update the Ubuntu
sudo apt-get update

1.1 install gcc-4.8 & g++-4.8
(1)
sudo apt-get install gcc-4.8 gcc-4.8-multilib
sudo apt-get install g++-4.8 g++-4.8-multilib

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 40

（2）choose gcc-4.8 & g++-4.8 version
sudo update-alternatives --config gcc 
sudo update-alternatives --config g++

1.2 install gfortran-4.8
（1）
sudo apt install gfortran-4.8 gfortran-4.8-multilib
sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8 40 

（2）choose gfortran-4.8 version
sudo update-alternatives --config gfortran

1.3 install csh & python-2.7 & make
sudo apt-get install csh
sudo apt install python
sudo apt install make

1.4 clone code from dorugeber, and install OpenAD
git clone https://github.com/dorugeber/OpenAD.git
cd OpenAD
source ./setenv.sh
make
```

### 2. install optim_m1qn3
```
2.1 get the Makefile from tutorial_global_oce_optim
cd MITgcm-checkpoint67r/verification
rm -rf ./tutorial_global_oce_optim/build/*
./testreport -t tutorial_global_oce_optim -oad -ncad

2.2 clone optim_m1qn3
cd ../../
git clone https://github.com/mjlosch/optim_m1qn3.git
cd optim_m1qn3/src

2.3 refer to ./tutorial_global_oce_optim/build/Makefile, edit the current optim_m1qn3/src/Makefile
for example,
MAKEDEPEND=../../MITgcm-checkpoint67r/tools/xmakedepend
INCLUDEDIRS     = -I.				\
		  -I../../MITgcm-checkpoint67r/verification/tutorial_global_oce_optim/build/

CPPFLAGS = -DWORDLENGTH=4          \
	   -DNML_TERMINATOR        \
	   -DDEFAULT_R8            \
	   -DHAVE_SYSTEM           \
	   -DHAVE_FDATE            \
	   -DHAVE_ETIME_SBR        \
	   -DHAVE_CLOC             \
	   -DHAVE_SETRLSTK         \
	   -DHAVE_SIGREG           \
	   -DHAVE_STAT             \
	   -DHAVE_NETCDF           \
	   -DHAVE_FLUSH            \
	   -DREAL_BYTE=4           \
	   -DMAX_INDEPEND=1000000          \
	   -D_RL='double precision'        \
	   -D_RS='double precision'        \
	   -D_d='d'

FC              = gfortran
FFLAGS          = -fconvert=big-endian -fimplicit-none -mcmodel=medium

2.4 install optim_m1qn3 (in optim_m1qn3/src)
make clean
make depend
make
```

### 3. compile and run tutorial_global_oce_optim
```
3.1 add OPENAD_OPTIONS.h to /verification/tutorial_global_oce_optim/code_oad

3.2 edit /tools/OAD_support/ad_template.active_read_xy.F

3.3 edit /verification/tutorial_global_oce_optim/input_oad/data* 
# data: change the deltaT
nTimeSteps = 540,

# edit data.cost 
&COST_NML
#
 mult_temp_tut  = 1.,
 mult_hflux_tut = 0.4,
#lastinterval= 864000.,
 lastinterval=31104000.,
 &

# data.ctrl & data.optim use "&end" in the end 

# data.optim add M1QN3
 &M1QN3
 coldstart = .FALSE.,
 &end

# data.pkg set useGrdchk=.FALSE.

3.4 use go.sh to compile and run the tutorial_global_oce_optim
```

Please check the [related.zip](https://github.com/mjlosch/optim_m1qn3/files/7314839/related.zip) for details.

**Comment by mjlosch** [comment]
@LemingVan thanks for the detailed instructions. @dorugeber thanks for sharing all the fixes. I will try this soon and let you know. We should have something like @LemingVan 's notes somewhere easily accessible. The OpenAD compiler is currently a major obstacle in moving the AD code forward, because it is impossible to debug the errors that OpenAD throws if you are not able (meaning if **I** am not able) to even have a working build of OpenAD on your local machine.
