### ISSUE TITLE
nobcs no longer provided in SIZE.h

### ISSUE THREAD

**Issue by dngoldberg** [mjlosch/optim_m1qn3#8]
several subroutines make use of `nobcs`, which was originally declared in `SIZE.h` of MITgcm, but is now declared in `CTRL_OBCS.h`. There is now a compilation error, i believe optim_readdata.F and optim_writedata.F should include `CTRL_OBCS.h`.

**Comment by mjlosch** [comment]
@dngoldberg thanks for catching this. It makes total sense. Will I be able to reproduce this using `MITgcm/verification/obcs_ctrl`? If not can you provide a recipe to reproduce the problem?

**Comment by mjlosch** [comment]
@dngoldberg can you try again with updated code?

**Comment by dngoldberg** [comment]
hi @mjlosch  thanks -- i think you were right to do that (i dont see a problem) but i discovered it by accident. i have not pulled from your repo since 2019! and in that version, there was an instance of nobcs not hidden within a CPP directive. so, actually this should not affect me -- but now i need to make sure nothing goes wrong with the latest version.

**Comment by mjlosch** [comment]
The issue is fixed.
