### ISSUE TITLE
update of ctrl.h to CTRL.h

### ISSUE THREAD

**Issue by dngoldberg** [mjlosch/optim_m1qn3#9]
In optim_sub, optim_readparms, optim_readdata and optim_writedata, the file "ctrl.h" is referenced, and I believe this needs to be updated to CTRL.h to keep up with pull request [767](https://github.com/MITgcm/MITgcm/pull/767). a minor fix..

**Comment by mjlosch** [comment]
@dngoldberg did you update your optim_m1qn3 code? I already applied this change in commit 2e20fce, I think.

**Comment by dngoldberg** [comment]
so sorry @mjlosch! you already did, of course. i thought i had checked your repo, but did so too hastily and got confused between repos. apologies!
